baseurl = "https://Kieran262.github.io/Blog_ca_nhan_network/"
title = "Blog lập trình mạng - Vũ Trường Thịnh"
theme = "DoAn"
themesDir = ".."
languageCode = "vi-vn"
preserveTaxonomyNames = true
hasCJKLanguage = true

[services]
  # Enable comments by entering your Disqus shortname
  [services.disqus]
    shortname = ""
  [services.googleAnalytics]
    id = ""

[pagination]
  pagerSize = 5 # frontpage pagination

[outputs]
home = ["HTML", "RSS", "Algolia"]

[params]
  header_image = "img/home-bg-jeep.jpg"
  SEOTitle = "Blog lập trình mạng | Vũ Trường Thịnh"
  description = "Blog cá nhân của Vũ Trường Thịnh chia sẻ kiến thức lập trình Java, JavaScript và ứng dụng trong lập trình mạng dành cho người mới bắt đầu."
  keyword = "lập trình mạng, Java, JavaScript, socket, HTTP, WebSocket, blog học lập trình, Vũ Trường Thịnh"
  slogan = "Học vững nền tảng, hiểu rõ kết nối"
  upstreamAttribution = true

  image_404 = "img/404-bg.jpg"
  title_404 = "你来到了没有知识的荒原 :("
  omit_categories = false

  # leancloud storage for page view counter
  page_view_counter = false
  leancloud_app_id = ""
  leancloud_app_key = ""

  # algolia site search
  algolia_search = true
  algolia_appId = ""
  algolia_indexName = ""
  algolia_apiKey = ""

  # Sidebar settings
  sidebar_about_description = "Xin chào, mình là **Vũ Trường Thịnh** – sinh viên yêu thích lập trình mạng, Java và JavaScript. Đây là nơi mình ghi lại kiến thức và kinh nghiệm học tập của bản thân."
  #sidebar_avatar = "img/avatar-zhaohuabing.jpg"      # use absolute URL, seeing it's used in both `/` and `/about/`
  sidebar_avatar = "img/avt.jpg"      # có thể thay bằng ảnh cá nhân trong thư mục static/img

  featured_tags = true 
  featured_condition_size = 1 

  # Baidu Analytics
  ba_track_id = ""
  
  # We need a proxy to access Disqus api in China
  # Follow https://github.com/zhaohuabing/disqus-php-api to set up your own disqus proxy
  disqus_proxy = ""
  disqus_site = ""

  # Twikoo comments
  # Follow https://twikoo.js.org/ to set up your own env_id
  twikoo_env_id = ""

  # Artalk comments
  # Follow https://artalk.js.org/ to set up your own server
  artalk_enable = true
  artalk_server = "https://xxx.xxx.com"
  artalk_site = "xxx blog"

  #Enable wechat pay & alipay to allow readers send reward money if they like the articles 
  reward = true 
  # reward_guide = "如果这篇文章对你有用,请随意打赏" 

  friends = true
  bookmarks = false
  about_me = true

  # Last posts
  last_posts = true
  #last_posts_title = "LAST POSTS"
  #last_posts_count = 5

  # Include any custom CSS and/or JS files, url or relative to /static folder
  custom_css = ["css/custom.css"]
  #custom_js = ["js/lightbox.js", "https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js", "js/main.js"]

  [params.social]
  rss            = true 
  email          = "youremail@example.com"
  #facebook      = "full profile url in facebook"
  #googleplus    = "full profile url in googleplus"
  #twitter       = "full profile url in twitter"
  linkedin       = ""
  stackoverflow  = ""
  #instagram     = "full profile url in instagram"
  github         = "https://github.com/your-github-username"
  wechat         = ""
  #medium        = "full profile url in medium"
  #slack         = "full workspace url in slack"
  #pinterest     = "full profile url in pinterest"
  #reddit        = "full profile url in reddit"
  #gitlab        = "full profile url in gitlab"
  #mastodon      = "full profile url in mastodon"
  #keybase       = "full profile url in keybase"
  #xing          = "https://www.xing.com/profile/yourxingid"
  #git           = "full profile url for git user"
  
  [[params.friend_link]]
  title = "Tài liệu Java chính thức"
  href =  "https://docs.oracle.com/javase"

  [[params.bookmark_link]]
  title =  "MDN JavaScript"
  href =  "https://developer.mozilla.org/vi/docs/Web/JavaScript"
  [[params.bookmark_link]]
  title = "Hướng dẫn Hugo"
  href =  "https://gohugo.io/documentation/"
  
  [[params.additional_menus]]
  title =  "BLOG"
  href =  "/blog"

[outputFormats.Algolia]
baseName = "algolia"
isPlainText = true
mediaType = "application/json"
notAlternative = true

[params.algolia]
vars = ["title", "summary", "date", "publishdate", "expirydate", "permalink"]
params = ["categories", "tags"] 

[markup]
  [markup.tableOfContents]
    endLevel = 2
    startLevel = 1
  [markup.highlight]
    style = "dracula"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]

[mediaTypes]
  [mediaTypes.'font/woff']
    suffixes = ['woff']
  [mediaTypes.'font/woff2']
    suffixes = ['woff2']
